#web:
 #   image: my-laravel-image
  #  ports:
   #     - 8000:8000
   # volumes:
   #     - ./:/app
version: '3.5'
services:
  app:
    build:
      context: ./
    volumes:
      - .:/var/www
    ports:
      - "8000:8000"
    environment:
      - APP_ENV=local
